[project]
name = "advent-of-code"
version = "2024.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
]
