#!/bin/sh

# Installs the AoC 2024 python environment.

set -e

# ----------#
# Globals #
# ----------#
UV_EXEC=${UV_EXEC:-"uv"}

# ------------#
# Functions #
# ------------#

# -------#
# Main #
# -------#
main() {
  # Sync python project.
  ${UV_EXEC} sync --group docs
}
main "${@}"


