#!/bin/sh

# Installs the AoC 2024 python environment.

set -e

# ----------#
# Globals #
# ----------#
YEAR=2024
UV_EXEC=${UV_EXEC:-"uv"}


# ------------#
# Functions #
# ------------#

# -------#
# Main #
# -------#
main() {
  # Move into year directory.
  cd "${YEAR}"

  # Install python project.
  ${UV_EXEC} sync --no-dev
}
main "${@}"


